web-scraping implementation
Syncano/syncano-socket-simple-web-scraping pull request #1
Opened 2018-03-01 10:40 UTC by Andela-callen

### What does this PR do?
- Scrapes webpage and returns xpath or css selectors in xml or json format.

2018-03-13 14:12 UTC, adamwardecki requested changes
Problems that I see here:
1. The way of passing config object is not in line with the docs
2. The scraping (with css at least) returns an extracted text from the selected element. What would be more useful is an html string (or an array of html strings).
3. I noticed that when trying to pass a css class as a scraping parameter (i.e. "image":"div.featured-thumbnail"), I'm getting an error. It should be possible to do this and receive an array of elements that match this css

2018-03-13 14:12 UTC, adamwardecki commented on socket.yml
> +description: Description of simple-web-scraper
Update the description

2018-03-13 14:12 UTC, adamwardecki commented on README.md
> +| selectorType | string | Indicates the type of selector to use in scraing | xpath | Contents can be scraped using either `xpath` or `css` selector.
s/scraing/scraping

2018-03-13 14:12 UTC, adamwardecki commented on socket.yml
> +        example: "https://funnycatsgallery.com/'"
There's an extra single quote after the url.

2018-03-13 14:12 UTC, adamwardecki commented on src/utility.js
> +        const isCssValue = $(config[value]).each((i, cssValue) => {
declaring isCssValue const is not needed here

2018-03-13 14:12 UTC, adamwardecki commented on src/utility.js
> +          decodedCss[i] = `${$(cssValue).text()}`;
$(cssValue).html()

2018-03-13 14:12 UTC, adamwardecki commented on src/utility.js
> +              decodedCss.toString();
Probably just `decodedCss`

2018-03-13 14:12 UTC, adamwardecki commented on socket.yml
> +        example: |
The example says that I should pass a `config` object along with rest of the params. My initial understanding was that the whole params object would look like this:

```js
{"url": "https://funnycatsgallery.com/", "selectorType": "css", "extract": "json", "config": {"image":"div.featured-thumbnail","title":"h1#logo"}}
```

but I it needs to be like so:

```js
{"url": "https://funnycatsgallery.com/", "selectorType": "css", "extract": "json", "image":"div.featured-thumbnail","title":"h1#logo"}
```

The first approach seems to be better.

2018-03-13 14:12 UTC, adamwardecki commented on src/scraping.js
> +    if (requestMethod === 'GET') {
Why GET?

2018-03-13 14:12 UTC, adamwardecki commented on src/scraping.js
> +const rp = require('request-promise');
`import rp from 'request-promise`

2018-03-17 16:17 UTC, Andela-callen commented on src/scraping.js
> +    if (requestMethod === 'GET') {
A `POST` would be preferred as the user is send information to the server.

2018-03-19 06:26 UTC, Andela-callen commented on README.md
> +| selectorType | string | Indicates the type of selector to use in scraing | xpath | Contents can be scraped using either `xpath` or `css` selector.
done

2018-03-19 06:28 UTC, Andela-callen commented on socket.yml
> +description: Description of simple-web-scraper
done

2018-03-19 06:30 UTC, Andela-callen commented on socket.yml
> +        example: "https://funnycatsgallery.com/'"
done

2018-03-19 06:33 UTC, Andela-callen commented on src/scraping.js
> +    if (requestMethod === 'GET') {
done

2018-03-19 06:33 UTC, Andela-callen commented on src/scraping.js
> +const rp = require('request-promise');
done

2018-03-19 12:03 UTC, Andela-callen commented on src/utility.js
> +        const isCssValue = $(config[value]).each((i, cssValue) => {
fixed

2018-03-19 12:03 UTC, Andela-callen commented on src/utility.js
> +          decodedCss[i] = `${$(cssValue).text()}`;
done

2018-03-19 12:04 UTC, Andela-callen commented on src/utility.js
> +              decodedCss.toString();
fixed

2018-03-26 10:28 UTC, adamwardecki approved these changes

2018-03-26 10:30 UTC, adamwardecki requested changes
The updated socket should also use the @syncano/cli package

2018-03-27 12:50 UTC, adamwardecki approved these changes

2018-03-27 12:50 UTC, merged